[config]
model = "gpt-4o"
language = "ko"

[pr_reviewer]
language = "ko"
num_code_suggestions = 5

[pr_description]
language = "ko"

[pr_code_suggestions]
language = "ko"

[pr_questions]
language = "ko"

[improve]
language = "ko"

[ask]
language = "ko"

[test]
language = "ko"

[describe]
language = "ko"

[update_changelog]
language = "ko"
